Parameters:
  StageParam:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
Resources:
  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: !Join ["", ["reactlytics-", Ref: StageParam]]
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
Outputs:
  ReactlyticsTableName:
    Value: !Ref MainTable
    Export:
      Name: !Join ["-", [ReactlyticsTableName, Ref: StageParam]]
  ReactlyticsTableArn:
    Value: !GetAtt MainTable.Arn
    Export:
      Name: !Join ["-", [ReactlyticsTableArn, Ref: StageParam]]
