name: Deploy Master
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: "Deploy master"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_SERVERLESS }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_SERVERLESS }}
      STAGE: prod
      AWS_DEFAULT_REGION: "us-east-1"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install
      - run: yarn cf:update-db
      - run: ./node_modules/.bin/sls deploy --stage ${{ env.STAGE }}
